import { registerProductHandlers } from './product.handlers';
import { registerCustomerHandlers } from './customer.handlers';
import { registerSaleHandlers } from './sale.handlers';
import { registerExpenseHandlers } from './expense.handlers';
import { registerSettingsHandlers } from './settings.handlers';
import { registerSystemHandlers } from './system.handlers';
import { registerSupplierHandlers } from './supplier.handlers';
import { registerCategoryHandlers } from './category.handlers';
import { registerUnitHandlers } from './unit.handlers';
import { registerBrandHandlers } from './brand.handlers';
import { registerPurchaseHandlers } from './purchase.handlers';
import { registerStockMovementHandlers } from './stockMovement.handlers';
import { registerSupplierPaymentHandlers } from './supplierPayment.handlers';
import { registerAccountingHandlers } from './accounting.handlers';
import { registerQuoteHandlers } from './quote.handlers';
import { registerInvoiceHandlers } from './invoice.handlers';
import { registerInvoicePaymentHandlers } from './invoicePayment.handlers';
import { registerTaxHandlers } from './tax.handlers';
import { registerBankHandlers } from './bank.handlers';
import { registerReportHandlers } from './report.handlers';
import { registerAuthHandlers } from './auth.handlers';
import { registerBackupHandlers } from './backup.handlers';
import { registerBranchHandlers } from './branch.handlers';
import { registerClassHandlers } from './class.handlers';
import { registerBudgetHandlers } from './budget.handlers';
import { registerRecurringHandlers } from './recurring.handlers';
import { registerEmployeeHandlers } from './employee.handlers';
import { registerCurrencyHandlers } from './currency.handlers';
import { registerInventoryHandlers } from './inventory.handlers';
import { registerImportExportHandlers } from './importExport.handlers';
import { registerReceiptHandlers } from './receipt.handlers';
import { registerReturnHandlers } from './return.handlers';
import { registerDiscountHandlers } from './discount.handlers';
import { registerNotificationHandlers } from './notification.handlers';
import { registerKhataHandlers } from './khata.handlers';
import { registerCashierShiftHandlers } from './cashierShift.handlers';
import { registerDashboardHandlers } from './dashboard.handlers';

export function registerDatabaseIpc() {
  console.log('[IPC Registration] Activating secure SQLite database channels...');
  registerAuthHandlers();
  registerProductHandlers();
  registerCustomerHandlers();
  console.log('[IPC Registration] Registering sale handlers...');
  registerSaleHandlers();
  console.log('[IPC Registration] Sales handlers registered: sales:getReceiptDetail, sales:void, sales:getAuditTrail');
  registerExpenseHandlers();
  registerSettingsHandlers();
  registerSystemHandlers();
  registerSupplierHandlers();
  registerCategoryHandlers();
  registerUnitHandlers();
  registerBrandHandlers();
  registerPurchaseHandlers();
  registerStockMovementHandlers();
  registerSupplierPaymentHandlers();
  registerAccountingHandlers();
  registerQuoteHandlers();
  registerInvoiceHandlers();
  registerInvoicePaymentHandlers();
  registerTaxHandlers();
  registerBankHandlers();
  registerReportHandlers();
  registerBackupHandlers();
  registerBranchHandlers();
  registerClassHandlers();
  registerBudgetHandlers();
  registerRecurringHandlers();
  registerEmployeeHandlers();
  registerCurrencyHandlers();
  registerInventoryHandlers();
  registerImportExportHandlers();
  registerReceiptHandlers();
  registerReturnHandlers();
  registerDiscountHandlers();
  registerNotificationHandlers();
  registerKhataHandlers();
  registerCashierShiftHandlers();
  registerDashboardHandlers();
  console.log('[IPC Registration] Secure database channel binding completed successfully.');
}
