import { ipcMain } from 'electron';
import { AuthRepository } from '../repositories/AuthRepository';
import { ReportRepository } from '../repositories/ReportRepository';

export function registerReportHandlers() {
  const requireReports = (token: string) => AuthRepository.requirePermission(token, 'reports.view');
  const requireBranch = (token: string, branchId?: string) => {
    requireReports(token);
    if (branchId) AuthRepository.requireBranchAccess(token, branchId);
  };

  ipcMain.handle('reports:profitAndLoss', (_, token: string, dateFrom: string, dateTo: string, branchId?: string, classId?: string) => { requireBranch(token, branchId); return ReportRepository.profitAndLoss({ dateFrom, dateTo, branchId, classId }); });
  ipcMain.handle('reports:balanceSheet', (_, token: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.balanceSheet(dateTo, branchId); });
  ipcMain.handle('reports:cashFlow', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.cashFlow({ dateFrom, dateTo }); });
  ipcMain.handle('reports:trialBalance', (_, token: string, dateFrom: string, dateTo: string, branchId?: string, classId?: string) => { requireBranch(token, branchId); return ReportRepository.trialBalance({ dateFrom, dateTo, branchId, classId }); });
  ipcMain.handle('reports:generalLedger', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.generalLedger({ dateFrom, dateTo }); });
  ipcMain.handle('reports:arAging', (_, token: string, dateTo: string) => { requireReports(token); return ReportRepository.arAging(dateTo); });
  ipcMain.handle('reports:apAging', (_, token: string, dateTo: string) => { requireReports(token); return ReportRepository.apAging(dateTo); });
  ipcMain.handle('reports:inventoryValuation', (_, token: string) => { requireReports(token); return ReportRepository.inventoryValuation(); });
  ipcMain.handle('reports:taxSummary', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.taxSummary({ dateFrom, dateTo }); });
  ipcMain.handle('reports:salesByCustomerProduct', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.salesByCustomerProduct({ dateFrom, dateTo }); });
  ipcMain.handle('reports:purchasesBySupplierProduct', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.purchasesBySupplierProduct({ dateFrom, dateTo }); });
  ipcMain.handle('reports:expenseSummary', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.expenseSummary({ dateFrom, dateTo }); });
  ipcMain.handle('reports:budgetVsActual', (_, token: string, dateFrom: string, dateTo: string, budgetId?: string, branchId?: string, classId?: string) => { requireBranch(token, branchId); return ReportRepository.budgetVsActual({ dateFrom, dateTo, budgetId, branchId, classId }); });
  ipcMain.handle('reports:classProfitAndLoss', (_, token: string, dateFrom: string, dateTo: string, branchId?: string, classId?: string) => { requireBranch(token, branchId); return ReportRepository.classProfitAndLoss({ dateFrom, dateTo, branchId, classId }); });
  ipcMain.handle('reports:customerBalance', (_, token: string) => { requireReports(token); return ReportRepository.customerBalanceReport(); });
  ipcMain.handle('reports:customerAging', (_, token: string, asOfDate: string) => { requireReports(token); return ReportRepository.customerAgingReport(asOfDate); });
  ipcMain.handle('reports:paymentCollection', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.paymentCollectionReport(dateFrom, dateTo); });
  ipcMain.handle('reports:shiftSummary', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.shiftSummaryReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:cashierDiscrepancy', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.cashierDiscrepancyReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:dailySalesSummary', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.dailySalesSummaryReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:productSales', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.productSalesReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:discountSummary', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.discountSummaryReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:returnSummary', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.returnSummaryReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:voidSummary', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.voidSummaryReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:paymentMethod', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.paymentMethodReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:cashDrawerReconciliation', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.cashDrawerReconciliationReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:branchPerformance', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.branchPerformanceReport(dateFrom, dateTo); });
  ipcMain.handle('reports:cashierSales', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.cashierSalesReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:hourlySales', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.hourlySalesReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:salesInvoices', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.salesInvoicesReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:purchaseSummary', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.purchaseSummaryReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:purchaseReturns', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.purchaseReturnsReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:stockMovement', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.stockMovementReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:lowStock', (_, token: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.lowStockReport(branchId); });
  ipcMain.handle('reports:branchStock', (_, token: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.branchStockReport(branchId); });
  ipcMain.handle('reports:inventoryAdjustment', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.inventoryAdjustmentReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:stockTransfer', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.stockTransferReport(dateFrom, dateTo); });
  ipcMain.handle('reports:customerStatement', (_, token: string, customerIdOrName: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.customerStatementReport(customerIdOrName, dateFrom, dateTo); });
  ipcMain.handle('reports:supplierPayable', (_, token: string, dateTo: string) => { requireReports(token); return ReportRepository.supplierPayableReport(dateTo); });
  ipcMain.handle('reports:supplierLedger', (_, token: string, supplierId: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.supplierLedgerReport(supplierId, dateFrom, dateTo); });
  ipcMain.handle('reports:supplierPayment', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.supplierPaymentReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:outputTax', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.outputTaxReport(dateFrom, dateTo); });
  ipcMain.handle('reports:inputTax', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.inputTaxReport(dateFrom, dateTo); });
  ipcMain.handle('reports:bankAccountSummary', (_, token: string) => { requireReports(token); return ReportRepository.bankAccountSummaryReport(); });
  ipcMain.handle('reports:moneyTransaction', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.moneyTransactionReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:bankReconciliation', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.bankReconciliationReport(dateFrom, dateTo); });
  ipcMain.handle('reports:branchProfitAndLoss', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.branchProfitAndLossReport(dateFrom, dateTo); });
  ipcMain.handle('reports:auditLog', (_, token: string, dateFrom: string, dateTo: string, userId?: string) => { requireReports(token); return ReportRepository.auditLogReport(dateFrom, dateTo, userId); });
  ipcMain.handle('reports:backupHistory', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.backupHistoryReport(dateFrom, dateTo); });
  ipcMain.handle('reports:notification', (_, token: string, dateFrom: string, dateTo: string, branchId?: string) => { requireBranch(token, branchId); return ReportRepository.notificationReport(dateFrom, dateTo, branchId); });
  ipcMain.handle('reports:userActivity', (_, token: string, dateFrom: string, dateTo: string) => { requireReports(token); return ReportRepository.userActivityReport(dateFrom, dateTo); });
}
